# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d0d3b0818144c0f36e5858423c0c3e3f45cec708b229772bc84bf6e27610ab9265e0efa507558cd5fd09203368fb2e92ce72e735b2da3e152a7a1f4aea3a7f

test:
  secret_key_base: 00a69b25eb534252cf4c8de3bd51433516acf8616ae1772e0044199dcdddcd208b81c3bb060bad19ad191aabc03b1bf514f40a81c89364e57b60a8689c8cc2a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
